# -*- coding: utf-8 -*-
"""task5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KZCpg9oE1XGu6kkIeVS8JczJKTf0OknS
"""

# ==========================================
# Decision Tree and Random Forest Classifier
# Heart Disease Dataset
# ==========================================

# Import libraries
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.tree import DecisionTreeClassifier, plot_tree
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# ------------------------------------------
# Load Dataset
# ------------------------------------------
df = pd.read_csv("heart.csv")

print("First 5 Rows:")
print(df.head())

print("\nDataset Shape:", df.shape)

# ------------------------------------------
# Separate Features and Target
# ------------------------------------------
X = df.drop("target", axis=1)
y = df["target"]

# ------------------------------------------
# Split Dataset
# ------------------------------------------
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

# ------------------------------------------
# Decision Tree Model
# ------------------------------------------
dt = DecisionTreeClassifier(max_depth=4, random_state=42)
dt.fit(X_train, y_train)

dt_pred = dt.predict(X_test)

print("\n===== Decision Tree =====")
print("Accuracy:", accuracy_score(y_test, dt_pred))

print("\nClassification Report:")
print(classification_report(y_test, dt_pred))

print("Confusion Matrix:")
print(confusion_matrix(y_test, dt_pred))

# ------------------------------------------
# Visualize Decision Tree
# ------------------------------------------
plt.figure(figsize=(18,10))

plot_tree(
    dt,
    feature_names=X.columns,
    class_names=["No Disease", "Disease"],
    filled=True,
    rounded=True
)

plt.title("Decision Tree")
plt.show()

# ------------------------------------------
# Random Forest Model
# ------------------------------------------
rf = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

rf.fit(X_train, y_train)

rf_pred = rf.predict(X_test)

print("\n===== Random Forest =====")
print("Accuracy:", accuracy_score(y_test, rf_pred))

print("\nClassification Report:")
print(classification_report(y_test, rf_pred))

print("Confusion Matrix:")
print(confusion_matrix(y_test, rf_pred))

# ------------------------------------------
# Feature Importance
# ------------------------------------------
importance = pd.DataFrame({
    "Feature": X.columns,
    "Importance": rf.feature_importances_
})

importance = importance.sort_values(by="Importance", ascending=False)

print("\nFeature Importance:")
print(importance)

# Plot Feature Importance
plt.figure(figsize=(10,6))

plt.bar(
    importance["Feature"],
    importance["Importance"]
)

plt.xticks(rotation=45)
plt.title("Random Forest Feature Importance")
plt.xlabel("Features")
plt.ylabel("Importance")

plt.tight_layout()
plt.show()

# ------------------------------------------
# Cross Validation
# ------------------------------------------
scores = cross_val_score(rf, X, y, cv=5)

print("\nCross Validation Scores:", scores)
print("Average Cross Validation Accuracy:", scores.mean())